Store.ready.then(() => {
  const data=Store.data,c=document.getElementById('content'),page=document.body.dataset.page,esc=Store.escapeHtml,money=Store.money;
  const me=Store.currentLandlord();
  if(!Store.isLandlordLoggedIn()||!me||me.status!=='APPROVED'){Store.logoutLandlord();location.href='login.html';return}
  document.getElementById('logoutBtn')?.addEventListener('click',()=>{Store.logoutLandlord();location.href='../index.html'});
  document.getElementById('menuBtn')?.addEventListener('click',()=>document.getElementById('sidebar')?.classList.toggle('open'));
  const myRooms=()=>data.rooms.filter(r=>r.landlordId===me.id);
  function dashboard(){const rs=myRooms();const active=data.rentals.filter(x=>x.status==='active'&&x.landlordId===me.id);c.innerHTML=`<div class="cards"><div class="card">My rooms<strong>${rs.length}</strong></div><div class="card">Available<strong>${rs.filter(r=>r.availability==='available').length}</strong></div><div class="card">Occupied<strong>${rs.filter(r=>r.availability==='occupied').length}</strong></div><div class="card">Active rentals<strong>${active.length}</strong></div></div><div class="section-gap"><h3>Assigned rooms</h3>${rs.map(r=>`<div class="admin-item"><b>${esc(r.name)}</b><br><small>${esc(r.location||'')} · ${money(r.companyPrice||r.price)}</small></div>`).join('')||'<div class="empty">No rooms have been assigned to you yet.</div>'}</div>`}
  function rooms(){const rs=myRooms();c.innerHTML=`<div class="admin-actions"><button class="btn primary" onclick="__landlord.edit()">+ Add room</button></div><div class="section-gap">${rs.length?rs.map(r=>`<div class="admin-item"><div class="admin-item-head"><div><b>${esc(r.name)}</b><br><small>${esc(r.location||'')} · ${money(r.landlordPrice||r.price)}</small></div><span class="status-pill ${r.availability==='available'?'':'pending'}">${esc(r.availability.toUpperCase())}</span></div><p>${esc(r.description||'')}</p><div class="admin-actions"><button class="btn primary" onclick="__landlord.edit('${r.id}')">Edit</button><button class="btn ghost" onclick="__landlord.photos('${r.id}')">Photos</button><button class="btn ghost" onclick="__landlord.toggle('${r.id}')">Mark ${r.availability==='available'?'occupied':'available'}</button></div></div>`).join(''):'<div class="empty">No rooms have been assigned to you yet.</div>'}</div>`}
  function payouts(){const rows=data.payouts.filter(x=>x.landlordId===me.id);const total=rows.reduce((s,x)=>s+Number(x.amount||0),0);c.innerHTML=`<div class="cards"><div class="card">Total payouts<strong>${money(total)}</strong></div><div class="card">Entries<strong>${rows.length}</strong></div></div><div class="section-gap">${rows.length?rows.map(x=>`<div class="admin-item"><b>${money(x.amount)}</b><br><small>${esc(x.note||'')} · ${new Date(x.date).toLocaleString()}</small></div>`).join(''):'<div class="empty">No payouts recorded yet.</div>'}</div>`}
  function edit(id){const r=id?myRooms().find(x=>x.id===id):null;if(id&&!r)return;c.innerHTML=`<button class="btn ghost" onclick="__landlord.go('properties')">Back</button><h3 class="section-gap">${r?'Edit room':'Add room'}</h3><form id="roomForm"><div class="form-grid"><label>Room name<input required name="name" value="${esc(r?.name||'')}"></label><label>Location<input required name="location" value="${esc(r?.location||'')}"></label><label>Landlord price<input required type="number" min="0" name="price" value="${r?.landlordPrice??''}"></label><label>Type<select name="type">${['Room','Apartment','Flat','House','Townhouse','Studio'].map(x=>`<option ${x===(r?.type||'Room')?'selected':''}>${x}</option>`).join('')}</select></label><label>Availability<select name="availability"><option value="available" ${r?.availability!=='occupied'?'selected':''}>Available</option><option value="occupied" ${r?.availability==='occupied'?'selected':''}>Occupied</option></select></label></div><label>Description<textarea name="description">${esc(r?.description||'')}</textarea><label>Facilities<input name="features" value="${esc((r?.features||[]).join(', '))}" placeholder="Parking, Shower, Wi-Fi"></label><label>Photos<input type="file" id="roomPhotos" accept="image/*" multiple></label><button class="btn primary">${r?'Save room':'Submit room'}</button></form>`;document.getElementById('roomForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),obj=r||{id:Store.uid('ROOM'),images:[],landlordId:me.id,approved:false};obj.name=f.get('name').trim();obj.location=f.get('location').trim();obj.landlordPrice=Number(f.get('price'));obj.type=f.get('type');obj.availability=f.get('availability');obj.description=f.get('description').trim();obj.features=f.get('features').split(',').map(x=>x.trim()).filter(Boolean);obj.landlordId=me.id;if(!r){obj.companyPrice=obj.landlordPrice;obj.price=obj.landlordPrice;data.rooms.push(obj);Store.save();Store.log('Landlord room submitted',`${obj.name} by ${me.name}`);alert('Room submitted for admin approval.')}else{Store.save();Store.log('Landlord room updated',obj.name)}go('properties')}}
  async function photos(id){const r=myRooms().find(x=>x.id===id);if(!r)return;c.innerHTML=`<button class="btn ghost" onclick="__landlord.go('properties')">Back</button><h3 class="section-gap">Photos — ${esc(r.name)}</h3><input id="roomPhotos" type="file" accept="image/*" multiple><div class="image-manager">${[0,1,2,3,4].map(i=>{const im=r.images?.[i];return `<div class="image-slot"><img src="${im?.startsWith('data:')?im:Store.DEFAULT_IMG}" data-local-img="${esc(im||'')}" alt=""><button type="button" class="btn ghost" ${im?'':'disabled'} onclick="__landlord.removeImage('${r.id}',${i})">Remove</button></div>`}).join('')}</div>`;Store.hydrateImages(c);document.getElementById('roomPhotos').onchange=async e=>{r.images=(r.images||[]).filter(x=>x&&x!=='default');for(const file of [...e.target.files]){if(r.images.length>=5)break;r.images.push(await Store.putImage(file))}Store.save();Store.log('Landlord photo updated',r.name);photos(id)}}
  function removeImage(id,i){const r=myRooms().find(x=>x.id===id);if(!r||!r.images?.[i])return;const old=r.images.splice(i,1)[0];Store.deleteImage(old);Store.save();Store.log('Landlord photo removed',r.name);photos(id)}
  function toggle(id){const r=myRooms().find(x=>x.id===id);if(!r)return;r.availability=r.availability==='available'?'occupied':'available';Store.save();Store.log('Landlord availability changed',`${r.name} → ${r.availability}`);rooms()}
  function go(target){({dashboard,properties:rooms,payouts}[target]||dashboard)()}
  window.__landlord={go,edit,photos,removeImage,toggle,render:()=>go(page)};Store.refresh();go(page);
});
